@baseUrl = http://localhost:3333
@authToken = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmODM2ZDgxYS1hYTI5LTRmNDAtYWUwNy1mMzdlMTcwNWY0NTkiLCJpYXQiOjE3MzAzNzAwMjB9.AEBMHQ9poaaC8adPnEvh1gv7GBhK1-Ym9JS0Ltg1qX42My2-btJZrJCUgq6jBk09i_kCYf8ia9D-AJ10VtCzsMMGD8kggIcRKnbsVG-Ns-HdPIPznXyvviHHzMKGsz-SSk-pRXpHcJYm5bV-82ogYZYvEnjxd0BT7sUKMFxKM7_hdDrtBDJciEKxGrj9DWWWt7RrlPyWoZ-dSaNgnGLlBwFQbaZ3-e96nMcQoL6plP7NGh4W9_iN0NV_-uouLGYtJvalv-k5SXXHQQyMDXoVxxTO8HYmE4cU9cJT75p8V_e-JUrgPO2LIT_Zum77X_oH1k1kh94FsF_83ihCjxnQ4A
@authToken2 = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name":"Gabriel Mattos",
  "email":"gabriel3@gmail.com",
  "password":"123456"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email":"gabriel3@gmail.com",
  "password":"123456"
}

###

# @name create_question
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken2}}

{
  "title": "Nova pergunta 5",
  "content": "Funciona, por favor.",
  "attachments":[]
}

###

# @name fetch_recent_questions
GET  {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken2}}

###

# 

POST {{baseUrl}}/questions/4e6846f2-79fc-4ef0-8111-1e1b05c2cb43/answers
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "content": "oi",
  "authorId": "f836d81a-aa29-4f40-ae07-f37e1705f459",
  "questionId": "4e6846f2-79fc-4ef0-8111-1e1b05c2cb43",
  "attachments": [],
  "attachmentsIds": []
}





